const express = require("express");
const router = express.Router();
const multer = require("../utils/multer");
const authController = require("../controller/auth.controller");
const isLoggedIn = require("../middleware/isLoggedIn");
router.route("/login").post(authController.login);
router.route("/signup").post(multer.uploadProfilePhoto, authController.signUp);
router.route("/deleteallusers").delete(authController.deletAllUsers);
router.route("/logout").get(authController.logout);
router.route("/isloggedin").get(isLoggedIn, authController.sendUserLoggedIn);
module.exports = router;
